<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\InvestmentPortfolioManager.Domain\InvestmentPortfolioManager.Domain.csproj" />
    <ProjectReference Include="..\InvestmentPortfolioManager.Application\InvestmentPortfolioManager.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
