apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  ASPNETCORE_ENVIRONMENT: Production
  JwtSettings__Issuer: https://api.portfolio.cdpq.com
  Cors__AllowedOrigins__0: https://portfolio.cdpq.com
  Cors__AllowedOrigins__1: https://www.cdpq.com
  Logging__LogLevel__Default: Warning
  Logging__LogLevel__Microsoft.AspNetCore: Error
  Features__EnableSwagger: "false"
  Features__EnableDetailedErrors: "false"
  Features__EnableMetrics: "true"
  Features__EnableTracing: "true"
  Features__EnableHealthChecks: "true"