apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-server-data-pvc
  labels:
    app.kubernetes.io/name: investment-portfolio-manager
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: sql-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-server-log-pvc
  labels:
    app.kubernetes.io/name: investment-portfolio-manager
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: sql-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  labels:
    app.kubernetes.io/name: investment-portfolio-manager
    app.kubernetes.io/component: cache
    app.kubernetes.io/instance: redis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-reports-pvc
  labels:
    app.kubernetes.io/name: investment-portfolio-manager
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: api
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: default